ALTER TABLE "ACCESS_LOGS"
    ADD COLUMN IF NOT EXISTS "request_id" VARCHAR(36),
    ADD COLUMN IF NOT EXISTS "error_type" VARCHAR(255),
    ADD COLUMN IF NOT EXISTS "error_message" VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS "stack_trace" TEXT;
