spring:
  profiles:
    default: local
  application:
    name: tech-log-back
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

app:
  image:
    public-path: /image
    max-total-size: 20MB
